server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:js|css|ttf|woff2?|png|jpg|jpeg|svg|mp3|ico)$ {
    expires 30d;
    access_log off;
  }
}
